/*
 * Copyright 2026 liuyu
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { Catalog } from './types';

/** Timeseries management, data management and database management. */
export const data: Catalog = {
  '测点': 'Timeseries',
  '创建测点': 'Create timeseries',
  '确定删除该测点吗？': 'Delete this timeseries?',
  '测点创建成功': 'Timeseries created',
  '测点删除成功': 'Timeseries deleted',
  '获取测点列表失败: {msg}': 'Failed to load the timeseries list: {msg}',
  '创建失败: {msg}': 'Create failed: {msg}',
  '删除失败: {msg}': 'Delete failed: {msg}',
  '目标设备': 'Target device',
  '上传 CSV': 'Upload CSV',
  '导出数据': 'Export data',
  '已导出 {n} 行': 'Exported {n} rows',
  '导出失败: {msg}': 'Export failed: {msg}',
  '这份 CSV 还没法导入': 'This CSV cannot be imported yet',
  '未找到 Time 列。导入要求每行带时间戳，请用本页面「导出数据」生成的 CSV。': 'No Time column was found. Import requires a timestamp on every row, so use a CSV generated by "Export data" on this page.',
  '除时间外没有可导入的列。': 'There is no importable column besides the time column.',
  '读取 CSV 失败: {msg}': 'Failed to read the CSV: {msg}',
  'root.sg.d1（列名只写测点名时必填）': 'root.sg.d1 (required when the column names are measurement names only)',
  'CSV 的列名如果只有测点名（temperature 而不是 root.sg.d1.temperature），就统统挂到这台设备下；列名本身带完整路径时以列名为准。树模型的设备路径必须以 root. 开头。': 'When a CSV column name is only a measurement name (temperature instead of root.sg.d1.temperature), every such column is attached to this device; when the column name is already a full path, the column name wins. In the tree model a device path must start with "root.".',
  '「目标设备」不是合法路径：树模型的设备必须以 root. 开头，只能含字母、数字、下划线或中文，不能带空格、引号或通配符。': '"Target device" is not a valid path: in the tree model a device must start with "root.", may contain only letters, digits, underscores or Chinese characters, and must contain no spaces, quotes or wildcards.',
  '列「{name}」不是合法的时间序列路径（不要带引号、空格或通配符）。': 'Column "{name}" is not a valid timeseries path (no quotes, spaces or wildcards).',
  '列「{name}」只有测点名、没有设备前缀——请在上方「目标设备」里填这批测点属于哪台设备。': 'Column "{name}" gives only a measurement name with no device prefix — fill in the "Target device" field above with the device these timeseries belong to.',
  '列「{name}」的设备段「{device}」必须以 root. 开头。': 'The device part "{device}" of column "{name}" must start with "root.".',
  '另有 {n} 列有同类问题。': '{n} more columns have the same kind of problem.',
  '导入预览：{name}': 'Import preview: {name}',
  '{rows} 行 × {cols} 列 / {devices} 个设备': '{rows} rows × {cols} columns / {devices} devices',
  '，跳过 {n} 行无有效时间戳': ', skipping {n} rows with no valid timestamp',
  '确认写入 IoTDB？': 'Confirm writing to IoTDB?',
  '将向 {devices} 个设备写入 {rows} 行，同时间戳的同测点会被覆盖。': 'This writes {rows} rows to {devices} devices; a timeseries with the same timestamp is overwritten.',
  '导入完成：{rows} 行 × {cols} 列 / {devices} 个设备': 'Import finished: {rows} rows × {cols} columns / {devices} devices',
  '导入失败: {msg}': 'Import failed: {msg}',
  '数据库名': 'Database name',
  '请输入数据库名': 'Please enter a database name',
  '创建数据库': 'Create database',
  '确定删除该数据库吗？': 'Delete this database?',
  '数据库创建成功': 'Database created',
  '数据库删除成功': 'Database deleted',
  '获取数据库列表失败: {msg}': 'Failed to load the database list: {msg}',
  'Schema 副本数': 'Schema replica count',
  '数据副本数': 'Data replica count',
  '时间分区间隔 (ms)': 'Time partition interval (ms)',
  'TTL (可选，单位：毫秒)': 'TTL (optional, in milliseconds)',
};
